### ISSUE TITLE
Library installation error

### ISSUE THREAD

**Issue by Cyberillc** [CPJiNan/AkariBan#2]
Pastebin link:[https://pastebin.com/vq4RVbxX](url)

**Comment by CPJiNan** [comment]
[libraries.zip](https://github.com/user-attachments/files/15688765/libraries.zip)
Hello!
It looks like you're having trouble connecting to the Taboolib repo source. 
Here’s a zipped version for you.
Please unzip the libraries folder into the root directory and restart your server.
