### ISSUE TITLE
插件权限

### ISSUE THREAD

**Issue by NanShengtEAM** [CPJiNan/AkariBan#4]
我是一个minecraft腐竹，想用权限组来让某些玩家也能使用类似的功能，师傅有权限节点以供添加？

**Comment by CPJiNan** [comment]
@NanShengtEAM 
该建议已在 3.1.6 版本被采纳。
请加QQ群 704109949 以便获取后续版本更新通知。

新增权限：
akariban.kick
akariban.ban
akariban.unban
akariban.whitelist
